name: BloodLedger
version: "0.1.1"
main: com.myst1cs04p.bloodledger.Main
api-version: 1.20

commands:
  bloodledger:
    description: Main command for BloodLedger plugin
    aliases: [bl]
    usage: /<command> <subcommand>
